### ISSUE TITLE
IWADs are out of date

### ISSUE THREAD

**Issue by Blastfrog** [mkrupczak3/Freedoom-for-Android#36]
0.12 was released just recently, perhaps the bundled IWADs should be updated.

**Comment by mkrupczak3** [comment]
Do the new iwads break backwards savegame compatibility? 

As it stands, I've only kind of hacked in how this app copies and handles iwads. I'm not sure if I have a good way yet of managing versions. So, a decision would have to be made to make it so:

1: forced update for everyone
2: choice to upgrade (hard)
3: new installs use later version (easy)

I'm opting for option 3.

**Comment by mkrupczak3** [comment]
Still need to fix armv8 support before I can push out any kind of update though (Google play requirements ugh). Procrastinating on that because I'm expecting it to be pretty hairy.

I'd welcome pull requests though

**Comment by mkrupczak3** [comment]
286389de67ed1c4406fbe914ad5aae048515b2e1

**Comment by mkrupczak3** [comment]
Published update to Google play blocked by #41, in the mean time please check out the release page on this github for a version with the updated wads.

Closing
