### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by DoomStar** [mkrupczak3/Freedoom-for-Android#38]
idk if this is the right place for this but i just wanna say something about this

I have played D-Touch before, and with it I could play multiplayer with my friends using the -host and -join commands.

Now, I found this gem and played it with little problems. I wanted to try multiplayer, so me and my friends attempt the -host and -join commands again. But now, after tapping launch game, the app goes into a black screen and doesn't respond.

Any way around this? Or is multiplayer with this app simply not supported?

**Comment by mkrupczak3** [comment]
Hi Doomstar,

Multiplayer is currently not supported in this app. I tried to hack it in when modifying nvllsum's "GZDoom for Android" by adding networking permissions to the app, but it seems getting networking worrying with code running in the android NDK is generally a bit trickier than just this simple change.

Supposedly, it would require something like writing some kind of network handler written in the Java portion that would serve requests made by the C/C++ portion

**Comment by mkrupczak3** [comment]
#41 is really plaguing me right now, and with how junky this app is put together right now I can't see multiplayer coming about too easily.

I welcome anyone to take a look at it, but for now I'm closing this issue under "won't fix". 

I think that this app could serve from a complete rewrite/rebase from beloko's delta touch, were he willing to publish parts of his app once again under the GPL.
