### ISSUE TITLE
most pk3s cause the game to close.

### ISSUE THREAD

**Issue by GoldenStarGamer** [mkrupczak3/Freedoom-for-Android#49]
as written, running preety much any pk3 with zscript will cause the game to close, and the fact that you cannot see gzdoom's loading text makes it harder to pinpoint what's causing it.  
It's very likely that this app uses a very outdated version of gzdoom, please update it, it's very anoying and I don't want to pay 2.50€ for delta-touch.

**Comment by Dalaxiss** [comment]
Some work tho, for example hdoom or brutal. Shame is you cant tell which one works and which one does not, before trying it.

**Comment by GoldenStarGamer** [comment]
> Some work tho, for example hdoom or brutal. Shame is you cant tell which one works and which one does not, before trying it.

why did you mention hdoom.

**Comment by Dalaxiss** [comment]
> > Some work tho, for example hdoom or brutal. Shame is you cant tell which one works and which one does not, before trying it.
> 
> why did you mention hdoom.

Because i play it a lot and its one of few that is well known and actually works.

**Comment by GoldenStarGamer** [comment]
> > > Some work tho, for example hdoom or brutal. Shame is you cant tell which one works and which one does not, before trying it.
> > 
> > 
> > why did you mention hdoom.
> 
> Because i play it a lot and its one of few that is well known and actually works.

have you got some kind of problem to "play it a lot".

**Comment by 7dog123** [comment]
> as written, running preety much any pk3 with zscript will cause the game to close, and the fact that you cannot see gzdoom's loading text makes it harder to pinpoint what's causing it. It's very likely that this app uses a very outdated version of gzdoom, please update it, it's very anoying and I don't want to pay 2.50€ for delta-touch.

This version runs GZDoom 2.1pre

**Comment by Mr795** [comment]
this is because this runs on a legacy version of GZDoom, which in turn is less capable than more recent versions.

**Comment by StarmanAkremis** [comment]
> this is because this runs on a legacy version of GZDoom, which in turn is less capable than more recent versions.

yeah, but is someone going to update it?

**Comment by mkrupczak3** [comment]
@GoldenStarGamer Seems unlikely at this time. I haven't been able to put as much time into this project as I would like. 

If you're amenable to a paid app, I highly recommend Belokogames' Delta Touch app. It has good support for newer GZDoom versions and contains numerous improvements to both the UI and GZDoom for phone compatibility

**Comment by StarmanAkremis** [comment]
@mkrupczak3 how hard would it be to port it myself?

**Comment by mkrupczak3** [comment]
@GoldenStarGamer Somewhat difficult, as Google deprecated the GNU C compiler in the Android Native Development Kit toolchain and GZDoom doesn't like to build with anything else.

You may be able to request the source code of the GZDoom fork(s) used by beloko game's Delta Touch if you buy a copy of that app. Not sure if he'd provide the launcher for it though.

**Comment by StarmanAkremis** [comment]
@mkrupczak3 ah bollocs

**Comment by Raypuia** [comment]
> You may be able to request the source code of the GZDoom fork(s) used by beloko game's Delta Touch if you buy a copy of that app. Not sure if he'd provide the launcher for it though.

That's not necessary (albeit useless), Delta Touch source code has always been open source since day one.
